server:
  name: project-local
  message: local 서버입니다.(변경 후2222)

executor:
  poolSize: 8

spring:
  redis:
    host: localhost
    port: 7000
    channel: ch01
    
  rabbitmq: # RabbitMQ 관련 설정
    host: localhost
    port: 5672
    username: local_rabbitmq_master
    password: local_rabbitmq
    queue: ch01
    exchange: product-exchange
    routing_key: foo.bar.#
