server:
  name: project-local
  message: local 서버입니다. 오늘 네번째 수정입니다.

executor:
  poolSize: 8

spring:
  redis:
    host: localhost
    port: 7000
    channel: ch01
    
  rabbitmq:
    queue: ch02
    exchange: product-exchange
